version: '3.0'
services:
  app_barplot:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/home/myuser/data:ro
    command: python /home/myuser/app_barplot.py

  app_histogram:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/home/myuser/data:ro
    command: python /home/myuser/app_histogram.py
